version: 0.0.{build}
skip_tags: true
image: Visual Studio 2015
environment:
  NUGETAPIKey:
    secure: f9WaafZZnjfL75Q+KWf0FNFJg3d+JrVRacP6h2QrQmiByV/quLEiJFyJwcBENP3G
  GITHUBUSER:
    secure: irLWtZzcq0FuQbrlCmKys9xE9bH4/Nd+LMBxzQOXXHs=
  GITHUBPASSWORD:
    secure: LFtOYE+LHqF2hEq5XYyszg==
nuget:
  project_feed: true
before_build:
  - ps: .\Build.ps1 -Target Restore
build_script:
- ps: .\Build.ps1 -Target Package
test_script:
- ps: .\build.ps1 -Target Test
artifacts:
- path: /Release/*.*
deploy_script:
- ps: .\build.ps1 -Target publish
notifications:
- provider: Email
  to:
  - wilfridtaylor@gmail.com
  subject: Build Completed
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
- provider: Email
  to:
  - w
  subject: Build Failed
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false